name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Set Versions
      uses: actions/github-script@v4
      id: set_version
      with:
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          const dash_index = no_v.lastIndexOf('-')
          const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
          core.setOutput('tag', tag)
          core.setOutput('no-v', no_v)
          core.setOutput('no-dash', no_dash)

    - name: Test things
      run: echo ${{steps.set_version.outputs.result}}

    - name: Test things
      run: echo ${{steps.set_version.outputs.tag}}

    - name: Test things2
      run: echo ${{steps.set_version.outputs.no-dash}}

    - name: Test things3
      run: echo ${{steps.set_version.outputs.tag}}

#    - name: Build and Push
#      uses: docker/build-push-action@v2
#      with:
#        push: true
#        tags: |
#          ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:latest
#          ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:${{steps.set-version.outputs.no-dash}}
