name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - uses: actions/github-script@v4
      id: set-version
      with:
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
          return {
            'tag': tag,
            'no-v': no_v,
            'no-dash': no_dash
          }

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:latest
          ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:${{steps.set-version.outputs.result.no-dash}}
