name: Test and Release
on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: ludeeus/action-shellcheck@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: the-image

      - run: docker run --rm the-image

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/release-')
    runs-on: ubuntu-latest
    steps:
      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_release = tag.replace('release-', '')
            const dash_index = no_release.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_release.substring(0, dash_index) : no_release
            core.setOutput('tag', tag)
            core.setOutput('no-release', no_release)
            core.setOutput('no-dash', no_dash)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:latest
            ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:${{steps.set_version.outputs.no-dash}}
