name: Test and Release
on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: ludeeus/action-shellcheck@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          load: true
          push: false
          tags: the-image

      - run: docker run --rm the-image google-java-format --version

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/release-')
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set Versions
        uses: actions/github-script@v6
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_release = tag.replace('release-', '')
            const dash_index = no_release.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_release.substring(0, dash_index) : no_release
            const parts = no_dash.split('.')
            if (parts.length != 3) {
              throw new Error(`Unexpected version ${no_dash}`)
            }
            const major = parts[0]
            const minor = parts[1]
            const subminor = parts[2]
            core.setOutput('major', major)
            core.setOutput('major-minor', `${major}.${minor}`)
            core.setOutput('major-minor-subminor', `${major}.${minor}.${subminor}`)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:latest
            ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:${{steps.set_version.outputs.major}}
            ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:${{steps.set_version.outputs.major-minor}}
            ${{secrets.DOCKERHUB_USERNAME}}/google-java-format:${{steps.set_version.outputs.major-minor-subminor}}
